theme: jekyll-theme-minimal
# Site settings
title: A.P
baseurl: 
url: "https://hyy.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: HU Yaoyuan
  desc: Passion & Curiosity
  email: huyaoyuanqaq@gmail.com
  selfie: assets/img/profile.jpeg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: Choccygogo
  google_plus:
  instagram: choccygogogo
  keybase:
  linkedin: https://www.linkedin.com/in/yaoyuan-hu-2a2126297/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
